from fastapi import APIRouter

from app.api.v1.endpoints import admin, addresses, auth, coupons, notifications, payments, restaurants, reviews, rider, users, customer
from app.api.v1 import admin as admin_portal
from app.api.v1 import restaurant
from app.api.v1 import rider as rider_portal

api_router = APIRouter()
api_router.include_router(auth.router, prefix="/auth", tags=["authentication"])
api_router.include_router(users.router, prefix="/users", tags=["users"])
api_router.include_router(restaurants.router, prefix="/restaurants", tags=["restaurants"])
api_router.include_router(addresses.router, prefix="/addresses", tags=["addresses"])
api_router.include_router(payments.router, prefix="/payments", tags=["payments"])
api_router.include_router(coupons.router, prefix="/coupons", tags=["coupons"])
api_router.include_router(reviews.router, prefix="/reviews", tags=["reviews"])
api_router.include_router(admin.router, prefix="/admin", tags=["admin"])
api_router.include_router(admin_portal.dashboard.router, prefix="/admin", tags=["admin"])
api_router.include_router(admin_portal.customers.router, prefix="/admin", tags=["admin"])
api_router.include_router(admin_portal.restaurants.router, prefix="/admin", tags=["admin"])
api_router.include_router(admin_portal.restaurant_owners.router, prefix="/admin", tags=["admin"])
api_router.include_router(admin_portal.riders.router, prefix="/admin", tags=["admin"])
api_router.include_router(admin_portal.orders.router, prefix="/admin", tags=["admin"])
api_router.include_router(admin_portal.delivery_assignments.router, prefix="/admin", tags=["admin"])
api_router.include_router(admin_portal.payments.router, prefix="/admin", tags=["admin"])
api_router.include_router(admin_portal.cod.router, prefix="/admin", tags=["admin"])
api_router.include_router(admin_portal.categories.router, prefix="/admin", tags=["admin"])
api_router.include_router(admin_portal.service_areas.router, prefix="/admin", tags=["admin"])
api_router.include_router(admin_portal.commissions.router, prefix="/admin", tags=["admin"])
api_router.include_router(admin_portal.coupons.router, prefix="/admin", tags=["admin"])
api_router.include_router(admin_portal.reports.router, prefix="/admin", tags=["admin"])
api_router.include_router(admin_portal.notifications.router, prefix="/admin", tags=["admin"])
api_router.include_router(admin_portal.audit_logs.router, prefix="/admin", tags=["admin"])
api_router.include_router(admin_portal.settings.router, prefix="/admin", tags=["admin"])
api_router.include_router(rider.router, prefix="/rider", tags=["rider"])
api_router.include_router(notifications.router, prefix="/notifications", tags=["notifications"])
api_router.include_router(customer.profile.router, prefix="/customer", tags=["customer"])
api_router.include_router(customer.addresses.router, prefix="/customer", tags=["customer"])
api_router.include_router(customer.restaurants.router, prefix="/customer", tags=["customer"])
api_router.include_router(customer.categories.router, prefix="/customer", tags=["customer"])
api_router.include_router(customer.products.router, prefix="/customer", tags=["customer"])
api_router.include_router(customer.search.router, prefix="/customer", tags=["customer"])
api_router.include_router(customer.location.router, prefix="/customer", tags=["customer"])
api_router.include_router(customer.cart.router, prefix="/customer", tags=["customer"])
api_router.include_router(customer.checkout.router, prefix="/customer", tags=["customer"])
api_router.include_router(customer.orders.router, prefix="/customer", tags=["customer"])
api_router.include_router(customer.tracking.router, prefix="/customer", tags=["customer"])
api_router.include_router(customer.favorites.router, prefix="/customer", tags=["customer"])
api_router.include_router(customer.notifications.router, prefix="/customer", tags=["customer"])
api_router.include_router(customer.payments.router, prefix="/customer", tags=["customer"])
api_router.include_router(customer.reviews.router, prefix="/customer", tags=["customer"])
api_router.include_router(customer.coupons.router, prefix="/customer", tags=["customer"])
api_router.include_router(restaurant.profile.router, prefix="/restaurant", tags=["restaurant"])
api_router.include_router(restaurant.dashboard.router, prefix="/restaurant", tags=["restaurant"])
api_router.include_router(restaurant.settings.router, prefix="/restaurant", tags=["restaurant"])
api_router.include_router(restaurant.status.router, prefix="/restaurant", tags=["restaurant"])
api_router.include_router(restaurant.hours.router, prefix="/restaurant", tags=["restaurant"])
api_router.include_router(restaurant.categories.router, prefix="/restaurant", tags=["restaurant"])
api_router.include_router(restaurant.products.router, prefix="/restaurant", tags=["restaurant"])
api_router.include_router(restaurant.orders.router, prefix="/restaurant", tags=["restaurant"])
api_router.include_router(rider_portal.profile.router, prefix="/rider", tags=["rider"])
api_router.include_router(rider_portal.verification.router, prefix="/rider", tags=["rider"])
api_router.include_router(rider_portal.documents.router, prefix="/rider", tags=["rider"])
api_router.include_router(rider_portal.vehicle.router, prefix="/rider", tags=["rider"])
api_router.include_router(rider_portal.status.router, prefix="/rider", tags=["rider"])
api_router.include_router(rider_portal.dashboard.router, prefix="/rider", tags=["rider"])
api_router.include_router(rider_portal.deliveries.router, prefix="/rider", tags=["rider"])
api_router.include_router(rider_portal.history.router, prefix="/rider", tags=["rider"])
api_router.include_router(rider_portal.earnings.router, prefix="/rider", tags=["rider"])
api_router.include_router(rider_portal.wallet.router, prefix="/rider", tags=["rider"])
api_router.include_router(rider_portal.notifications.router, prefix="/rider", tags=["rider"])
